"""Safe runtime inventory: no secrets, endpoints, database URLs, or case data."""

from risk_platform.config import Settings


def control_catalog(settings: Settings) -> dict:
    return {
        "release": "0.2.0",
        "deployment_scope": "single-process local development",
        "enterprise_ready": False,
        "live_api": [
            "bearer_authentication",
            "server_configured_role_permissions",
            "case_ownership",
            "domain_isolation",
            "bounded_body_and_headers",
            "body_read_deadline",
            "fixed_window_peer_rate_limit",
            "concurrency_limit",
            "trusted_hosts",
            "sanitized_errors",
            "security_response_headers",
            "redacted_structured_event_logs",
            "idempotent_case_creation",
            "transactional_audit",
            "postgres_append_only_audit",
            "validated_model_output",
            "model_timeout",
            "model_circuit_breaker",
        ],
        "tested_policy_library_not_yet_connected_to_agent_runtime": [
            "read_only_tool_allowlist",
            "case_scoped_evidence",
            "tool_call_and_time_budgets",
            "tool_output_limits",
            "citation_provenance",
            "insufficient_evidence_abstention",
            "mandatory_review_packet",
            "no_autonomous_business_actions",
            "default_deny_ai_egress",
            "classified_approved_evidence_only",
            "basic_sensitive_content_screen",
        ],
        "deployment_or_integration_pending": [
            "oidc_msal_mfa",
            "multi_user_role_assignment",
            "postgres_row_level_security",
            "distributed_quotas",
            "durable_langgraph_review_state",
            "qdrant_acl_filters",
            "azure_content_filters",
            "token_and_cost_budgets",
            "model_provenance_and_drift",
            "tls_kms_secret_manager",
            "egress_proxy_ssrf_protection",
            "siem_alerting",
            "retention_deletion_workflows",
            "external_immutable_audit_archive",
            "backup_restore_drills",
            "fairness_calibration_and_model_validation",
        ],
        "limits": {
            "max_body_bytes": settings.max_body_bytes,
            "max_header_bytes": settings.max_header_bytes,
            "requests_per_minute_per_peer": settings.requests_per_minute,
            "max_concurrent_requests": settings.max_concurrent_requests,
            "model_timeout_seconds": settings.model_timeout_seconds,
        },
        "switches": {
            "case_writes": settings.writes_enabled,
            "model_scoring": settings.scoring_enabled,
        },
        "limitations": [
            "In-process counters reset on restart and are not shared between workers.",
            "Local role simulation is not enterprise identity integration.",
            "Database owners can bypass audit triggers; separate roles and archives are required.",
            "Filters and citations cannot guarantee injection resistance or factual correctness.",
        ],
    }
